INSERT INTO moves (name) VALUES ('Kyykky');
INSERT INTO moves (name) VALUES ('Penkkipunnerrus');
INSERT INTO moves (name) VALUES ('Maastaveto');
INSERT INTO moves (name) VALUES ('Ylätalja');
INSERT INTO moves (name) VALUES ('Alatalja');
INSERT INTO moves (name) VALUES ('Selän ojennus');
INSERT INTO moves (name) VALUES ('Vipunosto taakse');
INSERT INTO moves (name) VALUES ('Hauiskääntö');
INSERT INTO moves (name) VALUES ('Vatsarutistus');
INSERT INTO moves (name) VALUES ('Vatsakierto');
INSERT INTO moves (name) VALUES ('Jalkojen loitonnus');
INSERT INTO moves (name) VALUES ('Jalkojen lähennys');
INSERT INTO moves (name) VALUES ('Penkkipunnerrus vino');
INSERT INTO moves (name) VALUES ('Ranskalainen punnerrus');
INSERT INTO moves (name) VALUES ('Vipunosto sivulle');
INSERT INTO moves (name) VALUES ('Vipunosto eteen');
INSERT INTO moves (name) VALUES ('Pystypunnerrus');